chore: run tombi in offline mode (#133)
There was an error in one CI job
(https://github.com/veecle/veecle-os/actions/runs/19131389848/job/54672749427):

```
Error: failed to fetch catalog: https://json.schemastore.org/api/json/catalog.json, reason: unexpected status: 503
```

I believe we are using internal schemas only so it shouldn't need to
download anything.

Signed-off-by: Wim Looman <wim.looman@veecle.io>